steps:
  - label: ":docker: :hammer:"
    plugins:
      docker-compose#v1.3.1:
        run: tests

  - label: ":shell: Lint"
    plugins:
      plugin-linter#v1.0.0:
        name: ecs-deploy

  - label: ":shell: Shellcheck"
    plugins:
      shellcheck#v1.0.1:
        files: hooks/**
